# Generated by Django 6.0.3 on 2026-03-05 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('dosis', models.CharField(max_length=100, verbose_name='Dosis')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Identificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('raza', models.CharField(max_length=100, verbose_name='Raza')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad (años)')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='veterinaria.cliente', verbose_name='Cliente')),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='veterinaria.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Mascota',
                'ordering': ['nombre'],
            },
        ),
    ]
