# Generated by Django 6.0.3 on 2026-03-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='bloqueado_por_intentos',
            field=models.BooleanField(default=False, verbose_name='Bloqueado por intentos fallidos'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='intentos_fallidos_login',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos fallidos de login'),
        ),
    ]
